### ISSUE TITLE
Missing build scripts

### ISSUE THREAD

**Issue by DaelonSuzuka** [rohankishore/ZenNotes#2]
Whatever build process you used to create the release should be included in scripts in the repository, so others can recreate the executables.

**Comment by rohankishore** [comment]
Noted. The pyinstaller command is:

```pyinstaller --onedir -w --icon="icon.ico" /main.py```

**Comment by rohankishore** [comment]
How can i add a build script to repo? Is it something like build.txt?

**Comment by DaelonSuzuka** [comment]
This is a python project, so why not use python?

You could make python script, `build.py`, that runs the pyinstaller command.

**Comment by rohankishore** [comment]
build.py added!
